name = "retpack"
author = "Rettend; based on ExPack by MAttila42"
version = "0.1.0"
description = "Vanilla survival, long-distance terrain, shaders, and technical building tools."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b61a48f04cad70714d1f0c72352c0e0de9529dc2bee8a130409f5086721cbf6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
